name: Docs Generation

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install latex and generate documents
      run: |
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-extra-utils poppler-utils pdf2svg
        cd ./ContinuousIntegration
        chmod +x ./run_generate_docs.sh
        ./run_generate_docs.sh
        mkdir result
        cp ../Documentation/Diagrams/*.png ../Documentation/Diagrams/*.svg result

    - name: Archive latex docs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Latex Documents
        path: ./ContinuousIntegration/result